### PR TITLE
Fix exercises that pass without changes

### PR DESCRIPTION
**Pull request by emschwartz**
Resolves https://github.com/tigerbeetle/tigerlings/issues/3

### CODE REVIEW

**Comment by JRI98** [comment]
Exercises 31, 32 and 33 now behave correctly.
However, exercise 10 stills passes if unchanged, in spite of the errors:
```
Running exercise: ./exercises/010_batch_limits.sh
[Server] info(message_bus): connection from client xxx
[Server] info(message_bus): peer performed an orderly shutdown: message_bus.MessageBusType(.replica).Connection.Peer{ .client = xxx }
[Client] info(message_bus): connected to replica 0
[Server] info(message_bus): connection from client yyy
[Server] info(message_bus): peer performed an orderly shutdown: message_bus.MessageBusType(.replica).Connection.Peer{ .client = yyy }
[Client] info(message_bus): connected to replica 0
[Client] thread xyz panic: reached unreachable code
[Client] .../tigerlings/tigerbeetle_repo/zig/lib/std/debug.zig:412:14: 0x1044148cf in assert (tigerbeetle)
[Client]     if (!ok) unreachable; // assertion failure
[Client]              ^
[Client] .../tigerlings/tigerbeetle_repo/src/vsr/client.zig:259:19: 0x104464f27 in request (tigerbeetle)
[Client]             assert(events.len <= constants.message_body_size_max);
[Client]                   ^
[Client] .../tigerlings/tigerbeetle_repo/src/repl.zig:738:32: 0x104464dc7 in send (tigerbeetle)
[Client]             repl.client.request(
[Client]                                ^
[Client] .../tigerlings/tigerbeetle_repo/src/repl.zig:490:34: 0x10446598f in do_statement (tigerbeetle)
[Client]                     try repl.send(state_machine_operation.?, statement.arguments);
[Client]                                  ^
[Client] .../tigerlings/tigerbeetle_repo/src/repl.zig:678:42: 0x104467977 in run (tigerbeetle)
[Client]                     try repl.do_statement(statement);
[Client]                                          ^
[Client] .../tigerlings/tigerbeetle_repo/src/tigerbeetle/main.zig:415:21: 0x104468737 in repl (tigerbeetle)
[Client]         try Repl.run(arena, args.addresses, args.cluster, args.statements, args.verbose);
[Client]                     ^
[Client] .../tigerlings/tigerbeetle_repo/src/tigerbeetle/main.zig:65:42: 0x104472b37 in main (tigerbeetle)
[Client]         .repl => |*args| try Command.repl(&arena, args),
[Client]                                          ^
[Client] .../tigerlings/tigerbeetle_repo/zig/lib/std/start.zig:524:37: 0x1044730e3 in main (tigerbeetle)
[Client]             const result = root.main() catch |err| {
[Client]                                     ^
[Client] ???:?:?: 0x19219a0df in ??? (???)
[Client] ???:?:?: 0xab3affffffffffff in ??? (???)
```

**Comment by emschwartz** [comment]
Thanks for checking! That last commit should ensure that it exits with a status code of 1

**Comment by JRI98** [comment]
It is fixed 👍

**Comment by emschwartz** [comment]
Thanks for reporting these issues!

If you have any other feedback on Tigerlings, please message me on the TigerBeetle community slack (or feel free to post more issues)! I'd love to hear what you thought of them.

**Pull request merged**
